### ISSUE TITLE
Possible False Positive in EL Injection

### ISSUE THREAD

**Issue by leesoh** [ilmila/J2EEScan#21]
I'm not sure whether this value is static or variable, but noticed a couple of false positives when the `#{584*540}` payload is submitted. The result of this expression being evaluated would be `315360`. Unfortunately this is a substring of `31536000`, which is the number of seconds in a year and, also, quite common as a value for `max-age` in the `Strict-Transport-Security` header.

**Comment by ilmila** [comment]
The strategy is dynamica, anyway some FP are still possible.
Evaluating new strategies to improve the detection.

**Comment by ilmila** [comment]
Changed strategy to avoid FP, commit e97bba64927ba7da097ea14584173d043c53bad6
