### ISSUE TITLE
struts with different file extensions

### ISSUE THREAD

**Issue by summitt** [ilmila/J2EEScan#6]
Hey, while scanning a struts app it was not picking up issues that should have been identified. While looking though the code i realized it only triggers on the common file extensions like .do and .action. These extensions are often customized for the organization. I manually updated the code to add the extensions that we use but it would be great if this could be configurable or even allowed to scan regardless of the file extension. For instance you don't even need to put a file extension on struts like www.example.com/test.action and www.example.com/test will work the same.

**Comment by ilmila** [comment]
Thank you for your feedback.

The fix will be pushed with a major version bump of the whole project in the next days.

**Comment by ilmila** [comment]
Release 1.2.5 fixes the issue. Thanks for reporting.
